import onesubseaLogo from "../assets/Images/onesubsea_logo.png";
import BakerHughesLogo from "../assets/Images/BakerHughes.png";
import UniversalBiofuelsLogo from "../assets/Images/UniversalBiofuels.png";
import LohiyaEdibleLogo from "../assets/Images/LohiyaEdible.png";
import Kaleesuwari from "../assets/Images/ksw_logo.png";
import Coromandel from "../assets/Images/CIL-logo.png";


export const factories = [
    {
      name: "One subsea",
      logo: onesubseaLogo,
      description: "Production, Manufacturing & Processing Technology",
      address: "23BP & 24OP, Vakalapudi, Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "https://www.onesubsea.slb.com/",
      status: "Accepted",
    },
    {
      name: "Baker Hughes SPS Service Base",
      logo: BakerHughesLogo,
      description: "Support Equipment lifecycle Management",
      address: "S and 6, 12A/1 Supply Base Facility, ONGC Logistics Park, Baker Hughes SPS Service Base, 12A/5A and 5B, ADB Road, Thammavaram, Andhra Pradesh 533005",
      link: "https://www.bakerhughes.com/subsea/subsea-services",
      status: "Accepted",
    },
    {
      name: "Universal Biofuels Private Limited",
      logo: UniversalBiofuelsLogo,
      description: "Industrial manufacturing of Renewable Chemicals, Fuels & Natural oils",
      address: "Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "http://www.universalbiofuelsltd.com/",
      status: "Accepted",
    },
    {
      name: "Lohiya Edible Oil Company",
      logo: LohiyaEdibleLogo,
      description: "Edible Oil Industry",
      address: "Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "https://lohiyagroup.in/",
      status: "Accepted",
    },
    {
      name: "Kaleesuwari Refinery & Industry Pvt. LTD",
      logo: Kaleesuwari,
      description: "Edible Oil, Oil & Natural Gas Company",
      address: "Phase-III, Industrial Park, Vakalapudi, Kakinada, Andhra Pradesh 533005",
      link: "https://kaleesuwari.com/",
      status: "Accepted",
    },
    {
      name: "Coromandel International ltd",
      logo: Coromandel,
      description: "Chemical plant",
      address: "87/A, Dr No16-22, Samalkota-Kakinada Bypass, Kakinada Port, Kakinada, Andhra Pradesh 533001",
      link: "https://www.coromandel.biz/",
      status: "Accepted",
    },
    {
      name: "One subsea",
      logo: onesubseaLogo,
      description: "Production, Manufacturing & Processing Technology",
      address: "23BP & 24OP, Vakalapudi, Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "https://www.onesubsea.slb.com/",
      status: "Waiting",
    },
    {
      name: "Baker Hughes SPS Service Base",
      logo: BakerHughesLogo,
      description: "Support Equipment lifecycle Management",
      address: "S and 6, 12A/1 Supply Base Facility, ONGC Logistics Park, Baker Hughes SPS Service Base, 12A/5A and 5B, ADB Road, Thammavaram, Andhra Pradesh 533005",
      link: "https://www.bakerhughes.com/subsea/subsea-services",
      status: "Waiting",
    },
    {
      name: "Universal Biofuels Private Limited",
      logo: UniversalBiofuelsLogo,
      description: "Industrial manufacturing of Renewable Chemicals, Fuels & Natural oils",
      address: "Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "http://www.universalbiofuelsltd.com/",
      status: "Waiting",
    },
    {
      name: "Lohiya Edible Oil Company",
      logo: LohiyaEdibleLogo,
      description: "Edible Oil Industry",
      address: "Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "https://lohiyagroup.in/",
      status: "Waiting",
    },
    {
      name: "Kaleesuwari Refinery & Industry Pvt. LTD",
      logo: Kaleesuwari,
      description: "Edible Oil, Oil & Natural Gas Company",
      address: "Phase-III, Industrial Park, Vakalapudi, Kakinada, Andhra Pradesh 533005",
      link: "https://kaleesuwari.com/",
      status: "Waiting",
    },
    {
      name: "Coromandel International ltd",
      logo: Coromandel,
      description: "Chemical plant",
      address: "87/A, Dr No16-22, Samalkota-Kakinada Bypass, Kakinada Port, Kakinada, Andhra Pradesh 533001",
      link: "https://www.coromandel.biz/",
      status: "Waiting",
    },
    {
      name: "One subsea",
      logo: onesubseaLogo,
      description: "Production, Manufacturing & Processing Technology",
      address: "23BP & 24OP, Vakalapudi, Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "https://www.onesubsea.slb.com/",
      status: "Resubmitted",
    },
    {
      name: "Baker Hughes SPS Service Base",
      logo: BakerHughesLogo,
      description: "Support Equipment lifecycle Management",
      address: "S and 6, 12A/1 Supply Base Facility, ONGC Logistics Park, Baker Hughes SPS Service Base, 12A/5A and 5B, ADB Road, Thammavaram, Andhra Pradesh 533005",
      link: "https://www.bakerhughes.com/subsea/subsea-services",
      status: "Resubmitted",
    },
    {
      name: "Universal Biofuels Private Limited",
      logo: UniversalBiofuelsLogo,
      description: "Industrial manufacturing of Renewable Chemicals, Fuels & Natural oils",
      address: "Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "http://www.universalbiofuelsltd.com/",
      status: "Resubmitted",
    },
    {
      name: "Lohiya Edible Oil Company",
      logo: LohiyaEdibleLogo,
      description: "Edible Oil Industry",
      address: "Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "https://lohiyagroup.in/",
      status: "Resubmitted",
    },
    {
      name: "Kaleesuwari Refinery & Industry Pvt. LTD",
      logo: Kaleesuwari,
      description: "Edible Oil, Oil & Natural Gas Company",
      address: "Phase-III, Industrial Park, Vakalapudi, Kakinada, Andhra Pradesh 533005",
      link: "https://kaleesuwari.com/",
      status: "Resubmitted",
    },
    {
      name: "Coromandel International ltd",
      logo: Coromandel,
      description: "Chemical plant",
      address: "87/A, Dr No16-22, Samalkota-Kakinada Bypass, Kakinada Port, Kakinada, Andhra Pradesh 533001",
      link: "https://www.coromandel.biz/",
      status: "Resubmitted",
    },
     {
      name: "One subsea",
      logo: onesubseaLogo,
      description: "Production, Manufacturing & Processing Technology",
      address: "23BP & 24OP, Vakalapudi, Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "https://www.onesubsea.slb.com/",
      status: "Pending",
    },
    {
      name: "Baker Hughes SPS Service Base",
      logo: BakerHughesLogo,
      description: "Support Equipment lifecycle Management",
      address: "S and 6, 12A/1 Supply Base Facility, ONGC Logistics Park, Baker Hughes SPS Service Base, 12A/5A and 5B, ADB Road, Thammavaram, Andhra Pradesh 533005",
      link: "https://www.bakerhughes.com/subsea/subsea-services",
      status: "Pending",
    },
    {
      name: "Universal Biofuels Private Limited",
      logo: UniversalBiofuelsLogo,
      description: "Industrial manufacturing of Renewable Chemicals, Fuels & Natural oils",
      address: "Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "http://www.universalbiofuelsltd.com/",
      status: "Pending",
    },
    {
      name: "Lohiya Edible Oil Company",
      logo: LohiyaEdibleLogo,
      description: "Edible Oil Industry",
      address: "Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "https://lohiyagroup.in/",
      status: "Pending",
    },
    {
      name: "Kaleesuwari Refinery & Industry Pvt. LTD",
      logo: Kaleesuwari,
      description: "Edible Oil, Oil & Natural Gas Company",
      address: "Phase-III, Industrial Park, Vakalapudi, Kakinada, Andhra Pradesh 533005",
      link: "https://kaleesuwari.com/",
      status: "Pending",
    },
    {
      name: "Coromandel International ltd",
      logo: Coromandel,
      description: "Chemical plant",
      address: "87/A, Dr No16-22, Samalkota-Kakinada Bypass, Kakinada Port, Kakinada, Andhra Pradesh 533001",
      link: "https://www.coromandel.biz/",
      status: "Pending",
    },
     {
      name: "One subsea",
      logo: onesubseaLogo,
      description: "Production, Manufacturing & Processing Technology",
      address: "23BP & 24OP, Vakalapudi, Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "https://www.onesubsea.slb.com/",
      status: "Verify",
    },
    {
      name: "Baker Hughes SPS Service Base",
      logo: BakerHughesLogo,
      description: "Support Equipment lifecycle Management",
      address: "S and 6, 12A/1 Supply Base Facility, ONGC Logistics Park, Baker Hughes SPS Service Base, 12A/5A and 5B, ADB Road, Thammavaram, Andhra Pradesh 533005",
      link: "https://www.bakerhughes.com/subsea/subsea-services",
      status: "Verify",
    },
    {
      name: "Universal Biofuels Private Limited",
      logo: UniversalBiofuelsLogo,
      description: "Industrial manufacturing of Renewable Chemicals, Fuels & Natural oils",
      address: "Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "http://www.universalbiofuelsltd.com/",
      status: "Verify",
    },
    {
      name: "Lohiya Edible Oil Company",
      logo: LohiyaEdibleLogo,
      description: "Edible Oil Industry",
      address: "Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "https://lohiyagroup.in/",
      status: "Verify",
    },
    {
      name: "Kaleesuwari Refinery & Industry Pvt. LTD",
      logo: Kaleesuwari,
      description: "Edible Oil, Oil & Natural Gas Company",
      address: "Phase-III, Industrial Park, Vakalapudi, Kakinada, Andhra Pradesh 533005",
      link: "https://kaleesuwari.com/",
      status: "Verify",
    },
    {
      name: "Coromandel International ltd",
      logo: Coromandel,
      description: "Chemical plant",
      address: "87/A, Dr No16-22, Samalkota-Kakinada Bypass, Kakinada Port, Kakinada, Andhra Pradesh 533001",
      link: "https://www.coromandel.biz/",
      status: "Verify",
    },
    {
      name: "One subsea",
      logo: onesubseaLogo,
      description: "Production, Manufacturing & Processing Technology",
      address: "23BP & 24OP, Vakalapudi, Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "https://www.onesubsea.slb.com/",
      status: "Rejected",
    },
    {
      name: "Baker Hughes SPS Service Base",
      logo: BakerHughesLogo,
      description: "Support Equipment lifecycle Management",
      address: "S and 6, 12A/1 Supply Base Facility, ONGC Logistics Park, Baker Hughes SPS Service Base, 12A/5A and 5B, ADB Road, Thammavaram, Andhra Pradesh 533005",
      link: "https://www.bakerhughes.com/subsea/subsea-services",
      status: "Rejected",
    },
    {
      name: "Universal Biofuels Private Limited",
      logo: UniversalBiofuelsLogo,
      description: "Industrial manufacturing of Renewable Chemicals, Fuels & Natural oils",
      address: "Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "http://www.universalbiofuelsltd.com/",
      status: "Rejected",
    },
    {
      name: "Lohiya Edible Oil Company",
      logo: LohiyaEdibleLogo,
      description: "Edible Oil Industry",
      address: "Kakinada Industrial Area, Kakinada, Andhra Pradesh 533005",
      link: "https://lohiyagroup.in/",
      status: "Rejected",
    },
    {
      name: "Kaleesuwari Refinery & Industry Pvt. LTD",
      logo: Kaleesuwari,
      description: "Edible Oil, Oil & Natural Gas Company",
      address: "Phase-III, Industrial Park, Vakalapudi, Kakinada, Andhra Pradesh 533005",
      link: "https://kaleesuwari.com/",
      status: "Rejected",
    },
    {
      name: "Coromandel International ltd",
      logo: Coromandel,
      description: "Chemical plant",
      address: "87/A, Dr No16-22, Samalkota-Kakinada Bypass, Kakinada Port, Kakinada, Andhra Pradesh 533001",
      link: "https://www.coromandel.biz/",
      status: "Rejected",
    },
  ];

export const irtDashboardData =[
          { label: "Total No incidents", value: 52 },
          { label: "Total Task", value: 22 },
          { label: "Completed Task", value: 52 },
          { label: "InProgress Task", value: 8 },
          { label: "Pending Task", value: 12 },
          { label: "Active Events", value: 5 },
          { label: "Active Incident", value: 13 },
        ]